E_voting/models.py
from enum import unique
# from validators import length
from E_voting import db, app
from sqlalchemy.sql import func
from flask_login import UserMixin
from E_voting import login_manager



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(length=30), nullable=False, unique=True)
    email = db.Column(db.String(length=30), nullable=False, unique=True)
    index = db.Column(db.String(length=40), nullable=False, unique=True)
    password = db.Column(db.String(50), nullable=False)
    date_created = db.Column(db.DateTime(timezone=True), nullable=False, default=func.now())
    team = db.Column(db.String(length=40), nullable=True, default=0)
    voterscount = db.relationship('Voterscount', backref='author', lazy=True, passive_deletes=True)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}')"


class Voterscount(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    voter_name = db.Column(db.String(50), nullable=False) 
    date_vote = db.Column(db.DateTime(timezone=True), nullable=False, default=func.now())
    voter = db.Column(db.Integer(), db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)# the user.id should be in ' ' and small letters

    def __repr__(self):
        return f"Voterscount('{self.voter}', '{self.date_vote}' )"

E_voting/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_sqlalchemy import SQLAlchemy
from flask_login import login_manager, LoginManager



app = Flask(__name__)


app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///voting.db'
app.config['SECRET_KEY'] = 'd6ac11bed59b75a6bmn4310nvbv4454ab'


bcrypt = Bcrypt(app)
db = SQLAlchemy(app)
login_manager = LoginManager()
login_manager.login_view = 'authent.login'
login_manager.init_app(app)
login_manager.login_message_category = 'info'


from E_voting.admin.routes import admin_panel
from E_voting.authentication.routes import authent
from E_voting.dashboard.routes import dashbrd
from E_voting.view.routes import views
from E_voting.errors.handlers import my_404
from E_voting.result.routes import result_display


app.register_blueprint(result_display, url_prefix='/')
app.register_blueprint(admin_panel, url_prefix='/')
app.register_blueprint(my_404, url_prefix='/')
app.register_blueprint(authent, url_prefix='/')
app.register_blueprint(dashbrd, url_prefix='/')
app.register_blueprint(views, url_prefix='/')
 

E_voting/admin/routes.py
from operator import index
from flask import Blueprint
from E_voting. models import User, Voterscount
from flask import flash, redirect, render_template, request, url_for, request
from flask_login import login_user, logout_user, current_user, login_required



admin_panel = Blueprint('admin_panel', __name__)



@admin_panel.route('/adminonlyHTU@2120/<int:post_id>', methods=['GET', 'POST'])
@login_required
def masterpage(post_id):
    user = current_user
    members = User.query.all()
    return render_template('masterpage.html', user=user, members=members, post_id=post_id)



@admin_panel.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out successfuly', category='success')
    return redirect(url_for('views.home'))
    return render_template('home.html')

E_voting/authentication/routes.py
from flask import Blueprint
from E_voting import db, bcrypt
from E_voting .models import User
from flask import get_flashed_messages
from .form import RegisterForm, LoginForm
from flask import flash, redirect, render_template, request, url_for, request
from flask_login import login_user, logout_user, current_user, login_required


authent = Blueprint('authent', __name__)

@authent.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data)
        user = User(username=form.username.data, email=form.email.data, index=form.index.data, password=hashed_pwd)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created successfully', category='success')
        return redirect(url_for('authent.login'))
    if form.errors != {}:
        for err_msg in form.errors.values():
            flash(f'Registration unsuccessful {err_msg}', category='error')
    return render_template('signup.html', form=form)
 


@authent.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            flash(f'Success! You are logged in as {user.email}', category='success')
            return redirect(url_for('dashbrd.dashboard'))
        else:
            flash('Login Uncessful. Please check email and password', category='error')
    return render_template('login.html', form=form)



@authent.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out successfuly', category='success')
    return redirect(url_for('views.home'))
    return render_template('home.html')

E_voting/dashboard/routes.py
from E_voting import db
from flask import Blueprint
from E_voting .models import User, Voterscount
from flask_login import login_required, current_user
from flask import redirect, render_template, request, flash, url_for



dashbrd = Blueprint('dashbrd', __name__)


@dashbrd.route('/dashboard')
@login_required
def dashboard():
    return render_template('voters.html')


@dashbrd.route('/votedashboard/', methods=['GET', 'POST'])
@login_required
def votedashboard():
    return render_template('votepage.html')

E_voting/result/routes.py
import random
from flask import Blueprint
from flask_login import current_user
from E_voting. models import User, Voterscount
from flask import render_template, redirect, flash
from E_voting import db

result_display = Blueprint('result_display', __name__)



def generate_id(sys_user):
    all_members = User.query.all()
    if len(all_members)  > 30:
        return "limit"
    else:
        myrandom = random.randint(2, 17)
        members = User.query.filter_by(team=str(myrandom)).all()
    
        print( "\n\n\n\n\n\n\n\n\n\n", len(all_members) )
        print(myrandom, len(members))
        if len(members) < 4:
            print("here works")
            if sys_user.team == str(0):
                sys_user.team = myrandom
                db.session.commit()
                return sys_user.team
            # sys_user = User.query.get(user.id)
            user = sys_user 
        else:
            return sys_user.team
            print( "\n\n\n\n\n\n\n\n\n\n", len(all_members) )
            if len(all_members) == 30:
                return sys_user.team
            else:
                flash('You have reach the limited number', category='error')
                generate_id(sys_user)



@result_display.route('/showresult', methods=['GET', 'POST'])
def showresult():
    
    user = current_user 
    sys_user = User.query.get(user.id)
    myrandom = generate_id(sys_user)
    members = User.query.filter_by(team=str(myrandom)).all()
        
    if user:
        flash('From X-CODERS)): thanks for your vote', category='success')
    return render_template('result.html', myrandom=myrandom, user=user, members=members)
    

E_voting/view/routes.py
from flask import Blueprint
from flask import redirect, request, render_template, flash


views = Blueprint('views', __name__)


@views.route('/')
@views.route('/home')
def home():
    return render_template('home.html')

E_voting/templates/404_error_page.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</head>
<body>
    <br><br>
    <div class="container">
    <div class="container">
        <h1>Opps this page does not exist ):</h1>
    <div class="spinner-grow text-primary" role="status">
        
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-secondary" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-success" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-danger" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-warning" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-info" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-light" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    <div class="spinner-grow text-dark" role="status">
        <span class="visually-hidden">Loading...</span>
    </div>
    </div>
    <br>
    <a href="{{ url_for('views.home')}}"><button class="btn btn-info">Back home</button></a>
    </div>
</body>
</html>

E_voting/templates/500_error_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</head>

<body>
    <br><br>
    <div class="container">
        <div class="container">
            <h1>Sorry we are experiencing a general problem ):</h1>
            <div class="spinner-grow text-primary" role="status">

                <span class="visually-hidden">Loading...</span>
            </div>
            <div class="spinner-grow text-secondary" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
            <div class="spinner-grow text-success" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
            <div class="spinner-grow text-danger" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
            <div class="spinner-grow text-warning" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
            <div class="spinner-grow text-info" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
            <div class="spinner-grow text-light" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
            <div class="spinner-grow text-dark" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
        <br>
        <a href="{{ url_for('views.home')}}"><button class="btn btn-info">Back home</button></a>
    </div>
</body>

</html>

E_voting/templates/adminlogin.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
    <title>{% block title %}Login Page{% endblock %}</title>
    {% endblock %}
</head>
<body class="bg-gradient-primary">
    {% block content %}
    <br>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
          <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
              <!-- Nested Row within Card Body -->
              <div class="row">
                <div class="col-lg-6 d-none d-lg-block">
                  <img src="{{url_for('static', filename='image/mp.png')}}" height="25" width="400">
                </div>
                <div class="col-lg-6">
                  <div class="p-5">
                    <div class="text-center">
                      <h1 class="h4 text-gray-900 mb-4"><strong>Login</strong></h1>
                    </div>
                    <form action="#" method="POST">
                      {{ form.hidden_tag() }} 
                      {{ form.email(class='form-control') }}
                      <br />
                      {{ form.password(class='form-control') }}
                      <br />
                      {{ form.submit(class='btn btn-primary btn-user btn-block') }}
                    </form>
                    <div class="text-center"><a class="small" href="{{ url_for('authent.signup')}}">
                        Create an Account!</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
</body>
</html>

E_voting/templates/adminsignup.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
    <title>{% block title %}Signup Page{% endblock %}</title>

    {% endblock %}
</head>
<body class="bg-gradient-primary">
    {% block content %}
    <br>
    <div class="container">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-5 d-none d-lg-block">
               <img src="{{url_for('static', filename='image/mp.png')}}" height="25" width="400">
            </div>
            <div class="col-lg-7">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                </div>

                <form action="" class="user" data-toggle="validator"method="POST">
                  {{ form.hidden_tag() }} 
                  {{ form.username(class='form-control')}}
                  <br />
                  {{ form.email(class='form-control') }}
                  <br />

                  <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                      {{ form.password(class='form-control') }}
                    </div>

                    <div class="col-sm-6">
                      {{ form.confirm_password(class='form-control') }}
                    </div>
                  </div>
                  <br />
                  {{ form.submit(class='btn btn-primary btn-user btn-block') }}
                </form>
                <div class="text-center">
                  <a class="small" href="{{ url_for('authent.login')}}">Already have an account? Login!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
</body>
</html>

E_voting/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <title>{% block title %}{% endblock %}</title>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   
    <!-- custom styling -->
    <link rel="stylesheet" href="{{ url_for('static', filename='cs.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-4.1.3/css/bootstrap.min.css')}}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-4.1.3/js/bootstrap.min.js')}}"/>
     <script src="https://kit.fontawesome.com/0c2d4f765d.js" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
 
  <body>
    <nav class="navbar navbar-expand-lg navbar-light ">
    <div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('views.home')}}"><img
        brand src="{{url_for('static', filename='/image/img.png')}}"height="37" width="37"alt="logo"/></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('views.home')}}">Home</a>
        </li>
      </ul>
      {% if current_user.is_authenticated %}
      <li class="nav-item">
         <a class="nav-link">Welcome,{{ current_user.username }}</a>
      </li>

      <ul class="navbar-nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"href="{{ url_for('authent.logout')}}">Logout</a>
        </li>
        {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('authent.login')}}">Login</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('authent.signup')}}">Signup</a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

 {% with messages = get_flashed_messages(with_categories=True) %} 
  {% if messages %} {% for category, message in messages %} 
  {% if category == "error" %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{ message }}
    <button class="close" data-dismiss="alert" type="button">&times;</button>
  </div>

  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{ message }}
    <button class="close" data-dismiss="alert" type="button">&times;</button>
  </div>
  {% endif %}{% endfor %}{% endif %}{% endwith %}


<!--====== jquery js ======-->
  <script src="{{url_for('static', filename='js/vendor/modernizr-3.6.0.min.js')}}"></script>
  <script src="{{url_for('static', filename='js/vendor/jquery-1.12.4.min.js')}}"></script>
  <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
  {% block content %}{% endblock %}
  </body>
</html>

E_voting/templates/home.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block head %}
    <title>{% block title %}Home page{% endblock %}</title>
    <!-- custom styling -->
    <link rel="stylesheet" href="{{ url_for('static', filename='cs.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-4.1.3/css/bootstrap.min.css')}}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-4.1.3/js/bootstrap.min.js')}}"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% endblock %}
  </head>
  <body class="bg-gradient-primary">
    {% block content %}
    <img src="{{url_for('static', filename='/image/rebb.jpg')}}" id="nm" />
    

    
    {% endblock %}
  </body>
</html>

E_voting/templates/login.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
    <title>{% block title %}Login Page{% endblock %}</title>
    {% endblock %}
</head>
<body class="bg-gradient-primary">
    {% block content %}
    <br>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
          <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
              <!-- Nested Row within Card Body -->
              <div class="row">
                <div class="col-lg-6 d-none d-lg-block">
                  <img src="{{url_for('static', filename='image/mp.png')}}" height="25" width="400">
                </div>
                <div class="col-lg-6">
                  <div class="p-5">
                    <div class="text-center">
                      <h1 class="h4 text-gray-900 mb-4"><strong>Login</strong></h1>
                    </div>
                    <form action="#" method="POST">
                      {{ form.hidden_tag() }} 
                      {{ form.email(class='form-control') }}
                      <br />
                      {{ form.password(class='form-control') }}
                      <br />
                      {{ form.submit(class='btn btn-primary btn-user btn-block') }}
                    </form>
                    <div class="text-center"><a class="small" href="{{ url_for('authent.signup')}}">
                        Create an Account!</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
</body>
</html>

E_voting/templates/votepage.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block head %}
    <title>{% block title %}Voter page{% endblock %}</title>
    
    <!-- custom styling -->
    <link rel="stylesheet" href="{{ url_for('static', filename='cs.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-4.1.3/css/bootstrap.min.css')}}"/>
    <link rel="stylesheet"href="{{ url_for('static', filename='/bootstrap-4.1.3/js/bootstrap.min.js')}}"/>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"/>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/0c2d4f765d.js" crossorigin="anonymous"></script>
    {% endblock %}
   


  </head>
  <body>
    {% block content %}
    <img src="{{url_for('static', filename='/image/rebbb.jpg')}}" />
    <br /><br />
    <div class="container">
      <div class="card text-center">
        <div class="card-header"><strong>The rebbles</strong></div>
        <div class="card-body">
          <h5 class="card-title"><strong></strong></h5>
          <div class="card mb-3" style="max-width: 540px">
            <div class="row g-0">
              <div class="col-md-4">
                <img src="{{ url_for('static', filename='/image/vers.jpg')}}"class="img-fluid rounded-start"alt="..."/>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"><strong>Speciality</strong>: </h5>
                  <p class="card-text"></p>
                  <p class="card-text">
                    <small class="text-muted">Last updated 3 mins ago</small>
                  </p>
                </div>
              </div>
            </div>
          </div> 
          <!-- <a href="" class="btn btn-primary"><strong>Generate ID</strong> <i class="fas fa-thumbs-up"></i></a> -->
          <a href="{{ url_for('result_display.showresult')}}" class="btn btn-primary"><strong>Generate ID </strong><i class='fas fa-vote-yea fa-spin fa-2x'></i></a>
        </div>
        <hr />
        <hr />

      </div>
    </div>
    {% endblock %}
  </body>
</html>

E_voting/templates/voters.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block head %}
    <title>{% block title %}Voters dashboard{% endblock %}</title>

    <!-- custom styling -->
    <link rel="stylesheet" href="{{ url_for('static', filename='cs.css') }}"/>
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='/style.css') }}"/> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-4.1.3/css/bootstrap.min.css')}}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap-4.1.3/js/bootstrap.min.js')}}"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% endblock %}
  </head>
  <body>
    {% block content %}
    <img src="{{url_for('static', filename='/image/rebbb.jpg')}}" />
    <br><br>
    <div class="container">
        <div class="card text-center">
        <div class="card-header"><strong>Welcome To The Rebels Voting Page</strong></div>
        <div class="card-body">
            <h5 class="card-title">(Let your vote count)</h5>
            <p class="card-text"><strong>Please vote wisely</strong></p>
            <a href="{{ url_for('dashbrd.votedashboard')}}" class="btn btn-primary">Proceed to Vote</a>
        </div>
        </div>
    </div> 
    {% endblock %}
  </body>
</html>